#!/usr/bin/env bash

mkdir -p "/tmp/rrun"

FILENAME=$1
if [[ "$FILENAME" == *.rs ]]
then
    SOURCE="${FILENAME}"
else
    SOURCE="${FILENAME}.rs"
fi

HASH=$(md5 -q $SOURCE)
DEST="/tmp/rrun/${FILENAME}_${HASH}"
shift

rustc "${SOURCE}" -o "${DEST}" && ${DEST} $@
